### ISSUE TITLE
undefined reference to `_imp___ZN11Color_WheelC1EP7QWidget'

### ISSUE THREAD

**Issue by mortalis13** [mbasaglia/Qt-Color-Picker#12]
Hi.
I'm trying to build the Designer plugin from the QtCreator.

But I get about 300 errors of type:

`undefined reference to ``_imp___ZN11Color_WheelC1EP7QWidget`

for files like:
- `color_wheel_plugin.cpp:45`
- `gradient_slider_plugin.cpp:50`

And the corresponding code for these two files:

`return new Color_Preview(parent);`

and

`return new Gradient_Slider(parent);`

I found the answers to questions where some `_imp___ZN...` references are missing. And the solution was to add libraries to the projetc, like:

- `QT += sql`
- `QT += network`

Could you advice something?
Thanks.

**Comment by mbasaglia** [comment]
Hello.

Try to clean and recompile.

Also what compiler and Qt version are you using?

**Comment by mortalis13** [comment]
Qt5 with MinGW

**Comment by mortalis13** [comment]
Tell me, can I run the `color_widgets_demo` directly or I should build the outer (`color_widgets.pro`) project first?

**Comment by mbasaglia** [comment]
All the .pro files are self-contained, they contain references to the relevant files so that everything gets compiled.

**Comment by mortalis13** [comment]
Ok.
Additionally there is a bunch of warning before those `_imp_ZN` errors, like:

`'void Abstract_Widget_List::removed(int)' redeclared without dllimport attribute after being referenced with dll linkage`

Maybe this will help. Here is the image:

![image](http://s8.postimg.org/3l99such1/color_dialog_errors.png)
Here I tried to build the demo project.

Another thing is that if I build using the Qt4 I don't get those errors, but have another error:

    definition of static data member 'Color_Wheel::staticMetaObjectExtraData' of dllimport'd class
     const QMetaObjectExtraData Color_Wheel::staticMetaObjectExtraData = {
                                ^
    Makefile.Debug:272: recipe for target '../out/obj/moc_color_wheel.o' failed

**Comment by mbasaglia** [comment]
The dllimport is windows-specific stuff I'm not too familiar with.

I pushed some changes, try to see if it works now.

**Comment by mortalis13** [comment]
Now I created new Qt project inside Qt Creator and copied needed `.cpp` and `.hpp` files one by one from the `src` and `include` folders:

    color_dialog.cpp
    color_preview.cpp
    color_selector.cpp
    color_wheel.cpp
    gradient_slider.cpp
    hue_slider.cpp

    color_dialog.hpp
    color_preview.hpp
    color_selector.hpp
    color_wheel.hpp
    colorpicker_global.hpp
    gradient_slider.hpp
    hue_slider.hpp
    paint_border.hpp

    color_dialog.ui

And again during the build the same errors. 
For example, the first error says:

`color_selector.cpp:42: error: undefined reference to _imp___ZN13Color_PreviewC2EP7QWidget`

And it directs me to the code:

    Color_Selector::Color_Selector(QWidget *parent) :
        error   =====>   Color_Preview(parent), p(new Private(this))
    {
        setUpdateMode(Continuous);
        p->old_color = color();

I think the builder complaints that the constructor calls its parent's constructor. 
That's weird...

Can it be comehow simplified so that I can see a part of the whole color widget. To include only one `.hpp` and debug it. Say to show only the **hue wheel** without other components?

**Comment by mortalis13** [comment]
I tested the new commit.
Now it works. 
But I checked the demo only. Later will try the plugin.

Thanks a lot for your time.

---

And the demo gives me this window:

![runs](https://cloud.githubusercontent.com/assets/10464927/7870483/4963472e-0592-11e5-952a-48a2b22dbcc8.png)

Is it normal? I mean those buttons above the "Add New".

**Comment by mortalis13** [comment]
Just checked the plugin building.
It builds with `qmake` and `make` correctly.
It works in the **Designer**.

To build it in the **Qt Creator** the project needs some additional adjustments because if I just open the plugin project and press **Configure Project** button the built `.dll` doesn't work with **Designer**. And it also has another filesize.

Thanks again.

**Comment by mbasaglia** [comment]
OK, good to know
